use crate::EngineError;
use crate::{HEADER_SIZE, Header, IndexEntry};
use anyhow::{Context, Result};
use memmap2::Mmap;

/// Storage handles the memory-mapped interface to the database file.
pub struct Storage {
    /// The raw memory map object from the OS.
    pub object: Mmap,
    /// A local copy of the file header for quick access to metadata.
    pub header: Header,
    /// Raw pointer to the index section to avoid self-referential struct limitations.
    /// This allows the struct to be Send/Sync and moved across thread boundaries.
    index_ptr: *const IndexEntry,
}

impl Storage {
    /// Initializes the engine by mapping the file and validating the header.
    pub fn new(path: &str) -> Result<Self, EngineError> {
        let file = std::fs::File::open(path).map_err(EngineError::Io)?;
        let mmap = unsafe { Mmap::map(&file).map_err(|e| EngineError::MmapFailed(e.to_string()))? };

        // 1. Protection: Ensure the file is large enough to contain a valid header.
        if mmap.len() < HEADER_SIZE {
            return Err(EngineError::InvalidHeader);
        }

        // 2. Handshake: Validate the magic number and version.
        let header_ptr = mmap.as_ptr() as *const Header;
        let header = unsafe { *header_ptr };

        if !header.is_valid() {
            return Err(EngineError::MagicMismatch);
        }

        // 3. Setup: Calculate the starting address of the index section.
        let index_ptr = unsafe { mmap.as_ptr().add(HEADER_SIZE) as *const IndexEntry };

        Ok(Storage {
            object: mmap,
            header,
            index_ptr,
        })
    }

    /// Private helper to interpret the raw index pointer as a safe Rust slice.
    /// This abstracts away the unsafe pointer arithmetic for the rest of the implementation.
    fn index(&self) -> &[IndexEntry] {
        unsafe { std::slice::from_raw_parts(self.index_ptr, self.header.count as usize) }
    }

    /// Performs a zero-copy lookup using binary search on the memory-mapped index.
    pub fn get(&self, key: u64) -> Option<&[u8]> {
        // Safe binary search using the slice generated by our internal helper.
        let pos = self.index().binary_search_by_key(&key, |e| e.key).ok()?;

        // Extract metadata for the value location.
        let entry = &self.index()[pos];
        let start = entry.val_offset as usize;
        let end = start + entry.val_len as usize;

        // Boundary check against the physical length of the mmap to prevent panics.
        if end > self.object.len() {
            return None;
        }

        // Return a direct reference to the mapped file memory.
        Some(&self.object[start..end])
    }
}

// Explicitly implement Send and Sync. Since the mmap is read-only after creation
// and we are not using internal mutability, it is safe to share across threads.
unsafe impl Send for Storage {}
unsafe impl Sync for Storage {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Header, IndexEntry};
    use std::fs;

    #[test]
    fn test_basic_retrieval() -> Result<(), Box<dyn std::error::Error>> {
        let path = "test_engine.db";
        let mut file_content = Vec::new();

        let header = Header {
            magic: 0xA016,
            version: 1,
            count: 1,
            padding: 0,
        };

        let entry = IndexEntry {
            key: 42,
            val_offset: 56, // Header (32) + 1 IndexEntry (24)
            val_len: 5,
            _padding: 0,
        };

        unsafe {
            let h_ptr = &header as *const Header as *const u8;
            file_content.extend_from_slice(std::slice::from_raw_parts(
                h_ptr,
                std::mem::size_of::<Header>(),
            ));

            let e_ptr = &entry as *const IndexEntry as *const u8;
            file_content.extend_from_slice(std::slice::from_raw_parts(
                e_ptr,
                std::mem::size_of::<IndexEntry>(),
            ));
        }

        file_content.extend_from_slice(b"hello");
        fs::write(path, file_content)?;

        let storage = Storage::new(path)?;
        let result = storage.get(42);

        assert!(result.is_some());
        assert_eq!(result.unwrap(), b"hello");

        fs::remove_file(path)?;
        Ok(())
    }
}
